/* ==========================
 * Strange Garden 舊版植物資料庫
 *
 * 用途：
 * - 保存舊版 Strange Garden 完整種植資料。
 * - 作為新版 foodstuff 相容層的基礎資料來源。
 * - 用於補齊新版已移除的種植相關參數。
 *
 * 說明：
 * - 新版多數物品預設不可種植，
 *   因此移除了 bed、days、season、
 *   multiplier 等種植設定。
 * - 相容層會以本資料庫補齊這些缺失，
 *   使舊版 Strange Garden 系統能正常運作。
 * ========================== */

/* globals Dict, PlantSetup */
// @ts-check

function initSGOldPlants() {
	/** @type {Dict<PlantSetup>} */
	const plants = {
		red_rose: {
			index: 0,
			name: "red_rose",
			plural: "红玫瑰",
			plant_cost: 400,
			difficulty: 1,
			bed: "earth",
			type: "flower", type_cn: "花朵",
			days: 14,
			multiplier: 1,
			special: [],
			season: ["spring", "autumn"],
			ingredients: [],
			icon: "red_rose.png",
		},

		white_rose: {
			index: 1,
			name: "white_rose",
			plural: "白玫瑰",
			plant_cost: 400,
			difficulty: 1,
			bed: "earth",
			type: "flower", type_cn: "花朵",
			days: 14,
			multiplier: 1,
			special: [],
			season: ["spring", "autumn"],
			ingredients: [],
			icon: "white_rose.png",
		},

		orchid: {
			index: 2,
			name: "orchid",
			plural: "兰花",
			plant_cost: 1000,
			difficulty: 2,
			bed: "earth",
			type: "flower", type_cn: "花朵",
			days: 28,
			multiplier: 1,
			special: [],
			season: ["summer"],
			ingredients: [],
			icon: "orchid.png",
		},

		daisy: {
			index: 3,
			name: "daisy",
			plural: "雏菊",
			plant_cost: 100,
			difficulty: 1,
			bed: "earth",
			type: "flower", type_cn: "花朵",
			days: 7,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn"],
			ingredients: [],
			icon: "daisy.png",
		},

		tulip: {
			index: 4,
			name: "tulip",
			plural: "郁金香",
			plant_cost: 200,
			difficulty: 1,
			bed: "earth",
			type: "flower", type_cn: "花朵",
			days: 12,
			multiplier: 1,
			special: [],
			season: ["autumn"],
			ingredients: [],
			icon: "tulip.png",
		},

		lotus: {
			index: 5,
			name: "lotus",
			plural: "睡莲",
			plant_cost: 300,
			difficulty: 2,
			bed: "water",
			type: "flower", type_cn: "花朵",
			days: 5,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "lotus.png",
		},

		lily: {
			index: 6,
			name: "lily",
			plural: "百合",
			plant_cost: 200,
			difficulty: 1,
			bed: "earth",
			type: "flower", type_cn: "花朵",
			days: 10,
			multiplier: 1,
			special: [],
			season: ["spring", "autumn"],
			ingredients: [],
			icon: "lily.png",
		},

		poppy: {
			index: 7,
			name: "poppy",
			plural: "罂粟",
			plant_cost: 200,
			difficulty: 2,
			bed: "earth",
			type: "flower", type_cn: "花朵",
			days: 8,
			multiplier: 1,
			special: [],
			season: ["spring", "autumn"],
			ingredients: [],
			icon: "poppy.png",
		},

		apple: {
			index: 8,
			name: "apple",
			plural: "苹果",
			plant_cost: 50,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 7,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "apple.png",
		},

		orange: {
			index: 9,
			name: "orange",
			plural: "橘子",
			plant_cost: 45,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 6,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "orange.png",
		},

		banana: {
			index: 10,
			name: "banana",
			plural: "香蕉",
			plant_cost: 70,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 9,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "banana.png",
		},

		lemon: {
			index: 11,
			name: "lemon",
			plural: "柠檬",
			plant_cost: 120,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 12,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "lemon.png",
		},

		blood_lemon: {
			index: 12,
			name: "blood_lemon",
			plural: "血柠",
			plant_cost: 400,
			difficulty: 2,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 20,
			multiplier: 1,
			special: ["aphrodisiac"],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "blood_lemon.gif",
		},

		pear: {
			index: 13,
			name: "pear",
			plural: "梨",
			plant_cost: 80,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 10,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "pear.png",
		},

		strawberry: {
			index: 14,
			name: "strawberry",
			plural: "草莓",
			plant_cost: 180,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 14,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "strawberry.png",
		},

		peach: {
			index: 15,
			name: "peach",
			plural: "桃子",
			plant_cost: 65,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 8,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "peach.png",
		},

		plum: {
			index: 16,
			name: "plum",
			plural: "李子",
			plant_cost: 80,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 10,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "plum.png",
		},

		mushroom: {
			index: 17,
			name: "mushroom",
			plural: "普通蘑菇",
			plant_cost: 100,
			difficulty: 1,
			bed: "wood",
			type: "shroom", type_cn: "菌类",
			days: 14,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "mushroom.png",
		},

		wolfshroom: {
			index: 18,
			name: "wolfshroom",
			plural: "狼菇",
			plant_cost: 300,
			difficulty: 1,
			bed: "wood",
			type: "shroom", type_cn: "菌类",
			days: 21,
			multiplier: 1,
			special: ["aphrodisiac"],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "wolfshroom.png",
		},

		wild_honeycomb: {
			index: 19,
			name: "wild_honeycomb",
			plural: "野蜂巢",
			plant_cost: 12000,
			difficulty: 3,
			bed: "hive",
			type: "produce", type_cn: "产品",
			days: 7,
			multiplier: 1,
			special: ["large"],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "wild_honeycomb.png",
		},

		wild_carrot: {
			index: 20,
			name: "wild_carrot",
			plural: "胡萝卜",
			plant_cost: 40,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 10,
			multiplier: 3,
			special: [],
			season: ["spring", "summer", "autumn"],
			ingredients: [],
			icon: "carrot.png",
		},

		onion: {
			index: 21,
			name: "onion",
			plural: "洋葱",
			plant_cost: 120,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 12,
			multiplier: 3,
			special: [],
			season: ["spring", "autumn"],
			ingredients: [],
			icon: "onion.png",
		},

		garlic_bulb: {
			index: 22,
			name: "garlic_bulb",
			plural: "大蒜",
			plant_cost: 100,
			difficulty: 2,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 8,
			multiplier: 3,
			special: [],
			season: ["autumn"],
			ingredients: [],
			icon: "garlic.png",
		},

		potato: {
			index: 23,
			name: "potato",
			plural: "马铃薯",
			plant_cost: 20,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 7,
			multiplier: 4,
			special: [],
			season: ["spring", "autumn", "winter"],
			ingredients: [],
			icon: "potato.png",
		},

		strange_flower: {
			index: 24,
			name: "strange_flower",
			plural: "诡异的花",
			plant_cost: 1000,
			difficulty: 3,
			bed: "earth",
			type: "flower", type_cn: "花朵",
			days: 28,
			multiplier: 1,
			special: ["aphrodisiac"],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "strange_flower.png",
		},

		truffle: {
			index: 25,
			name: "truffle",
			plural: "松露",
			plant_cost: 800,
			difficulty: 4,
			bed: "earth",
			type: "shroom", type_cn: "菌类",
			days: 28,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "truffle.png",
		},

		bottle_of_milk: {
			index: 26,
			name: "bottle_of_milk",
			plural: "瓶装牛奶",
			plant_cost: 100,
			difficulty: 1,
			bed: "cow",
			type: "produce", type_cn: "产品",
			days: 1,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "milk.png",
		},

		chicken_egg: {
			index: 27,
			name: "chicken_egg",
			plural: "鸡蛋",
			plant_cost: 40,
			difficulty: 1,
			bed: "chicken",
			type: "produce", type_cn: "产品",
			days: 1,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "egg.png",
		},

		bottle_of_breast_milk: {
			index: 28,
			name: "bottle_of_breast_milk",
			plural: "瓶装母乳",
			plant_cost: 3000,
			difficulty: 1,
			bed: "human",
			type: "produce", type_cn: "产品",
			days: 1,
			multiplier: 1,
			special: ["large"],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "breastmilk.png",
		},

		bottle_of_semen: {
			index: 29,
			name: "bottle_of_semen",
			plural: "瓶装精液",
			plant_cost: 3000,
			difficulty: 1,
			bed: "human",
			type: "produce", type_cn: "产品",
			days: 1,
			multiplier: 1,
			special: ["large"],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "semenbottle.png",
		},

		cabbage: {
			index: 30,
			name: "cabbage",
			plural: "卷心菜",
			plant_cost: 50,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 8,
			multiplier: 3,
			special: [],
			season: ["spring", "winter"],
			ingredients: [],
			icon: "cabbage.png",
		},

		turnip: {
			index: 31,
			name: "turnip",
			plural: "萝卜",
			plant_cost: 80,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 12,
			multiplier: 2,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "turnip.png",
		},

		broccoli: {
			index: 32,
			name: "broccoli",
			plural: "西兰花",
			plant_cost: 50,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 10,
			multiplier: 3,
			special: [],
			season: ["spring", "autumn"],
			ingredients: [],
			icon: "broccoli.png",
		},

		ghostshroom: {
			index: 33,
			name: "ghostshroom",
			plural: "幽灵菇",
			plant_cost: 200,
			difficulty: 1,
			bed: "wood",
			type: "shroom", type_cn: "菌类",
			days: 14,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "ghostshroom.png",
		},

		blackberry: {
			index: 34,
			name: "blackberry",
			plural: "黑莓",
			plant_cost: 7,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 10,
			multiplier: 10,
			special: ["small"],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "blackberry.png",
		},

		carnation: {
			index: 35,
			name: "carnation",
			plural: "康乃馨",
			plant_cost: 60,
			difficulty: 1,
			bed: "earth",
			type: "flower", type_cn: "花朵",
			days: 3,
			multiplier: 1,
			special: [],
			season: ["autumn"],
			ingredients: [],
			icon: "carnation.png",
		},

		bird_egg: {
			index: 36,
			name: "bird_egg",
			plural: "鸟蛋",
			plant_cost: 200,
			difficulty: 1,
			bed: "bird_nest",
			type: "produce", type_cn: "产品",
			days: 1,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "bird_egg.png",
		},

		baby_bottle_of_breast_milk: {
			index: 37,
			name: "baby_bottle_of_breast_milk",
			singular: "小瓶装母乳",
			plural: "小瓶装母乳",
			plant_cost: 200,
			difficulty: 1,
			bed: "human",
			type: "produce", type_cn: "产品",
			days: 1,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "babybottle.png",
		},

		plumeria: {
			index: 38,
			name: "plumeria",
			plural: "鸡蛋花",
			plant_cost: 320,
			difficulty: 1,
			bed: "earth",
			type: "flower", type_cn: "花朵",
			days: 12,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn"],
			ingredients: [],
			icon: "plumeria.png",
		},

		oyster_pearl: {
			index: 39,
			name: "oyster_pearl",
			singular: "牡蛎珍珠",
			plural: "牡蛎珍珠",
			plant_cost: 50000,
			difficulty: 1,
			bed: "oyster",
			type: "produce", type_cn: "产品",
			days: 1,
			multiplier: 1,
			special: ["large"],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "oyster_pearl.png",
		},

		bread: {
			index: 40,
			name: "bread",
			singular: "面包",
			plural: "面包",
			plant_cost: 100,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 20,
			multiplier: 1,
			special: ["vegan"],
			season: [],
			ingredients: ["flour", "salt", "vegetable_oil"],ingredients_cn: ["面粉", "盐", "植物油"],
			icon: "bread.png",
		},

		flour: {
			index: 41,
			name: "flour",
			singular: "面粉",
			plural: "面粉",
			plant_cost: 10,
			difficulty: 1,
			bed: "kitchen",
			type: "ingredient", type_cn: "食材",
			days: 20,
			multiplier: 10,
			special: [],
			season: [],
			ingredients: ["wheat"],ingredients_cn: ["小麦"],
			icon: "flour.png",
		},

		salt: {
			index: 42,
			name: "salt",
			singular: "盐",
			plural: "盐",
			plant_cost: 5,
			difficulty: 1,
			bed: "sea",
			type: "ingredient", type_cn: "食材",
			days: 20,
			multiplier: 10,
			special: [],
			season: [],
			ingredients: [],
			icon: "salt.png",
			shop: ["supermarket"],
			boughtInBulk: 25,
		},

		vegetable_oil: {
			index: 43,
			name: "vegetable_oil",
			singular: "植物油",
			plural: "植物油",
			plant_cost: 10,
			difficulty: 1,
			bed: "kitchen",
			type: "ingredient", type_cn: "食材",
			days: 20,
			multiplier: 10,
			special: [],
			season: [],
			ingredients: [],
			icon: "vegetable_oil.png",
			shop: ["supermarket"],
			boughtInBulk: 25,
		},

		pizza: {
			index: 44,
			name: "pizza",
			singular: "披萨",
			plural: "披萨",
			handheld_gift: true,
			plant_cost: 1200,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["bread", "tomato", "garlic_bulb", "cheese"],ingredients_cn: ["面包", "番茄", "大蒜", "芝士"],
			icon: "pizza.png",
		},

		tomato: {
			index: 45,
			name: "tomato",
			singular: "西红柿",
			plural: "西红柿",
			plant_cost: 30,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 10,
			multiplier: 4,
			special: [],
			season: ["summer", "autumn"],
			ingredients: [],
			icon: "tomato.png",
		},

		cheese: {
			index: 46,
			name: "cheese",
			singular: "芝士",
			plural: "芝士",
			plant_cost: 500,
			difficulty: 1,
			handheld_gift: true,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 60,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["bottle_of_milk"], ingredients_cn: ["牛奶"],
			ingredientIcon: "raw_cheese.png",
			icon: "cheese.png",
		},

		macaroni_cheese: {
			index: 47,
			name: "macaroni_cheese",
			recipe_name: "macaroni and cheese",
			singular: "奶酪通心粉",
			plural: "奶酪通心粉",
			plant_cost: 800,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 30,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["bottle_of_milk", "cheese", "flour", "pasta", "salt"],ingredients_cn: ["牛奶", "芝士", "面粉", "意大利面", "盐"],
			icon: "macaroni_cheese.png",
		},

		pasta: {
			index: 48,
			name: "pasta",
			singular: "意大利面",
			plural: "意大利面",
			plant_cost: 200,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 20,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["flour", "chicken_egg", "vegetable_oil", "salt"],ingredients_cn: ["面粉", "鸡蛋", "植物油", "盐"],
			icon: "pasta.png",
		},

		cauliflower_cheese: {
			index: 49,
			name: "cauliflower_cheese",
			singular: "奶酪花椰菜",
			plural: "奶酪花椰菜",
			plant_cost: 1000,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["cauliflower", "cheese", "garlic_bulb", "bottle_of_milk"], ingredients_cn: ["花椰菜", "芝士", "大蒜", "牛奶"],
			icon: "cauliflower_cheese.png",
		},

		wheat: {
			index: 50,
			name: "wheat",
			seed_name: "小麦",
			singular: "杯装小麦",
			plural: "杯装小麦",
			plant_cost: 10,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 9,
			multiplier: 5,
			special: [],
			season: ["spring", "summer", "autumn"],
			ingredients: [],
			icon: "wheat.png",
		},

		prawn_bisque: {
			index: 51,
			name: "prawn_bisque",
			singular: "鲜虾浓汤",
			plural: "鲜虾浓汤",
			plant_cost: 1500,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 1,
			special: ["seafood"],
			season: [],
			ingredients: ["prawn", "onion", "garlic_bulb", "vegetable_oil", "cream", "lemon"], ingredients_cn: ["大虾", "洋葱", "大蒜", "植物油", "奶油", "柠檬"],
			icon: "prawn_bisque.png",
		},

		cream: {
			index: 52,
			name: "cream",
			singular: "奶油",
			plural: "奶油",
			plant_cost: 100,
			difficulty: 1,
			bed: "cow",
			type: "produce", type_cn: "产品",
			days: 1,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: [],
			icon: "cream.png",
		},

		chelsea_bun: {
			index: 53,
			name: "chelsea_bun",
			recipe_name: "Chelsea buns",
			singular: "切尔西小圆面包",
			plural: "切尔西小圆面包",
			plant_cost: 200,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 60,
			multiplier: 4,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["flour", "salt", "butter", "sugar", "bottle_of_milk", "honey"], ingredients_cn: ["面粉", "盐", "黄油", "糖", "牛奶", "蜂蜜"],
			icon: "chelsea_bun.png",
		},

		honey: {
			index: 54,
			name: "honey",
			singular: "蜂蜜",
			plural: "蜂蜜",
			plant_cost: 10,
			difficulty: 1,
			bed: "kitchen",
			type: "ingredient", type_cn: "食材",
			days: 60,
			multiplier: 1200,
			special: [],
			season: [],
			ingredients: ["wild_honeycomb"], ingredients_cn: ["野生蜂巢"],
			icon: "honey.png",
		},

		butter: {
			index: 55,
			name: "butter",
			singular: "黄油",
			plural: "黄油",
			plant_cost: 10,
			difficulty: 1,
			bed: "kitchen",
			type: "ingredient", type_cn: "食材",
			days: 20,
			multiplier: 10,
			special: [],
			season: [],
			ingredients: ["bottle_of_milk"], ingredients_cn: ["牛奶"],
			icon: "butter.png",
		},

		naan_bread: {
			index: 56,
			name: "naan_bread",
			singular: "馕饼",
			plural: "馕饼",
			plant_cost: 200,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 20,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["bottle_of_milk", "flour", "vegetable_oil", "chicken_egg", "salt"], ingredients_cn: ["牛奶", "面粉", "植物油", "鸡蛋", "盐"],
			icon: "naan_bread.png",
		},

		pastry: {
			index: 57,
			name: "pastry",
			recipe_name: "pastries",
			singular: "酥皮",
			plural: "酥皮",
			plant_cost: 150,
			difficulty: 1,
			bed: "kitchen",
			type: "ingredient", type_cn: "食材",
			days: 20,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: ["butter", "flour", "salt"], ingredients_cn: ["黄油", "面粉", "盐"],
			icon: "pastry.png",
		},

		quiche: {
			index: 58,
			name: "quiche",
			singular: "法式咸派",
			plural: "法式咸派",
			plant_cost: 200,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 20,
			multiplier: 6,
			special: [],
			season: [],
			ingredients: ["pastry", "bottle_of_milk", "chicken_egg", "bacon", "cheese", "tomato"], ingredients_cn: ["酥皮", "牛奶", "鸡蛋", "培根", "芝士", "番茄"],
			icon: "quiche.png",
		},

		bacon: {
			index: 59,
			name: "bacon",
			singular: "培根薄片",
			plural: "培根薄片",
			plant_cost: 200,
			difficulty: 1,
			bed: "kitchen",
			type: "meat", type_cn: "肉类",
			days: 20,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: [],
			icon: "bacon.png",
			shop: ["supermarket"],
		},

		mince_pie: {
			index: 60,
			name: "mince_pie",
			singular: "百果馅饼",
			plural: "百果馅饼",
			plant_cost: 400,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 30,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["pastry", "blackberry", "sugar"], ingredients_cn: ["酥皮", "黑莓", "糖"],
			icon: "mince_pie.png",
		},

		sugar: {
			index: 61,
			name: "sugar",
			singular: "小勺糖",
			plural: "小勺糖",
			plant_cost: 5,
			difficulty: 1,
			bed: "kitchen",
			type: "ingredient", type_cn: "食材",
			days: 20,
			multiplier: 10,
			special: [],
			season: [],
			ingredients: [],
			icon: "sugar.png",
			shop: ["supermarket"],
			boughtInBulk: 25,
		},

		sausage_roll: {
			index: 62,
			name: "sausage_roll",
			recipe_name: "sausage rolls",
			singular: "香肠卷",
			plural: "香肠卷",
			plant_cost: 150,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 6,
			special: [],
			season: [],
			ingredients: ["pastry", "salt", "sausage", "chicken_egg", "lemon"], ingredients_cn: ["酥皮", "盐", "香肠", "鸡蛋", "柠檬"],
			icon: "sausage_roll.png",
		},

		sausage: {
			index: 63,
			name: "sausage",
			singular: "香肠",
			plural: "香肠",
			plant_cost: 200,
			difficulty: 1,
			bed: "kitchen",
			type: "meat", type_cn: "肉类",
			days: 20,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: [],
			icon: "sausage.png",
			shop: ["supermarket"],
		},

		potato_pancake: {
			index: 64,
			name: "potato_pancake",
			recipe_name: "potato pancakes",
			singular: "土豆煎饼",
			plural: "土豆煎饼",
			plant_cost: 100,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 10,
			multiplier: 4,
			special: ["vegetarian"],
			season: [],
			ingredients: ["potato", "onion", "chicken_egg", "vegetable_oil"], ingredients_cn: ["土豆", "洋葱", "鸡蛋", "植物油"],
			icon: "potato_pancake.png",
		},

		onion_bhaji: {
			index: 65,
			name: "onion_bhaji",
			recipe_name: "onion bhajis",
			singular: "洋葱巴哈吉",
			plural: "洋葱巴哈吉",
			plant_cost: 100,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 10,
			multiplier: 4,
			special: ["vegan", "spicy"],
			season: [],
			ingredients: ["flour", "onion", "chilli_pepper"], ingredients_cn: ["面粉", "洋葱", "辣椒"],
			icon: "onion_bhaji.png",
		},

		chilli_pepper: {
			index: 66,
			name: "chilli_pepper",
			singular: "辣椒",
			plural: "辣椒",
			plant_cost: 80,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 22,
			multiplier: 6,
			special: [],
			season: ["summer", "autumn"],
			ingredients: [],
			icon: "chilli_pepper.png",
		},

		samosa: {
			index: 67,
			name: "samosa",
			recipe_name: "samosas",
			singular: "咖喱角",
			plural: "咖喱角",
			plant_cost: 60,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 15,
			multiplier: 5,
			special: ["vegetarian", "spicy"],
			season: [],
			ingredients: ["pastry", "potato", "chilli_pepper", "lemon"], ingredients_cn: ["酥皮", "土豆", "辣椒", "柠檬"],
			icon: "samosa.png",
		},

		sweet_and_sour_chicken: {
			index: 68,
			name: "sweet_and_sour_chicken",
			singular: "糖醋鸡肉",
			plural: "糖醋鸡肉",
			plant_cost: 800,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 30,
			multiplier: 1,
			special: ["spicy"],
			season: [],
			ingredients: ["chicken", "vegetable_oil", "pepper", "sugar", "onion"], ingredients_cn: ["鸡肉", "植物油", "灯笼椒", "糖", "洋葱"],
			icon: "sweet_and_sour_chicken.png",
		},

		chicken: {
			index: 69,
			name: "chicken",
			singular: "鸡肉",
			plural: "鸡肉",
			plant_cost: 300,
			difficulty: 1,
			bed: "kitchen",
			type: "meat", type_cn: "肉类",
			days: 10,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: [],
			icon: "chicken.png",
			shop: ["supermarket"],
		},

		pepper: {
			index: 70,
			name: "pepper",
			singular: "灯笼椒",
			plural: "灯笼椒",
			plant_cost: 60,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 15,
			multiplier: 4,
			special: [],
			season: ["spring", "summer", "winter"],
			ingredients: [],
			icon: "pepper.png",
		},

		kedgeree: {
			index: 71,
			name: "kedgeree",
			singular: "鱼蛋烩饭",
			plural: "鱼蛋烩饭",
			plant_cost: 1600,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 1,
			special: ["seafood"],
			season: [],
			ingredients: ["haddock", "rice", "chicken_egg", "butter", "vegetable_oil", "lemon", "cream"],  ingredients_cn: ["黑线鳕鱼", "米", "鸡蛋", "黄油", "植物油", "柠檬", "奶油"],
			icon: "kedgeree.png",
		},

		rice: {
			index: 72,
			name: "rice",
			seed_name: "大米",
			singular: "杯装米",
			plural: "杯装米",
			plant_cost: 50,
			difficulty: 2,
			bed: "water",
			type: "vegetable", type_cn: "蔬菜",
			days: 26,
			multiplier: 20,
			special: [],
			season: ["spring", "summer", "autumn"],
			ingredients: [],
			icon: "rice.png",
		},

		haddock: {
			index: 73,
			name: "haddock",
			singular: "黑线鳕鱼",
			plural: "黑线鳕鱼",
			plant_cost: 600,
			difficulty: 2,
			bed: "sea",
			type: "seafood", type_cn: "海鲜",
			days: 1,
			multiplier: 1,
			special: [],
			season: ["summer", "autumn"],
			ingredients: [],
			icon: "haddock.png",
			shop: ["supermarket"],
		},

		honeyed_pork: {
			index: 74,
			name: "honeyed_pork",
			singular: "蜜汁猪肉",
			plural: "蜜汁猪肉",
			plant_cost: 1100,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 45,
			multiplier: 1,
			special: ["carnivore"],
			season: [],
			ingredients: ["pork", "salt", "honey", "chicken_egg"],  ingredients_cn: ["猪肉", "盐", "蜂蜜", "鸡蛋"],
			icon: "honeyed_pork.png",
		},

		beef_wellington: {
			index: 75,
			name: "beef_wellington",
			singular: "惠灵顿牛肉",
			plural: "惠灵顿牛肉",
			plant_cost: 1800,
			difficulty: 4,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 60,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: ["beef", "onion", "pastry", "chicken_egg", "salt", "mushroom"], ingredients_cn: ["牛肉", "洋葱", "酥皮", "鸡蛋", "盐", "蘑菇"],
			icon: "beef_wellington.png",
		},

		salmon_wellington: {
			index: 76,
			name: "salmon_wellington",
			singular: "惠灵顿鲑鱼",
			plural: "惠灵顿鲑鱼",
			plant_cost: 1800,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 60,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: ["salmon", "broccoli", "pastry", "chicken_egg", "salt"], ingredients_cn: ["鲑鱼", "西兰花", "酥皮", "鸡蛋", "盐"],
			icon: "salmon_wellington.png",
		},

		hamburger: {
			index: 77,
			name: "hamburger",
			recipe_name: "hamburgers",
			singular: "汉堡",
			plural: "汉堡",
			plant_cost: 600,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 15,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: ["beef", "bread", "onion", "tomato"],ingredients_cn: ["牛肉", "面包", "洋葱", "番茄"],
			icon: "burger.png",
		},

		cheeseburger: {
			index: 78,
			name: "cheeseburger",
			recipe_name: "cheeseburgers",
			singular: "芝士汉堡",
			plural: "芝士汉堡",
			plant_cost: 800,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 15,
			multiplier: 2,
			special: [],
			season: [],
			ingredients: ["beef", "bread", "onion", "tomato", "cheese"],ingredients_cn: ["牛肉", "面包", "洋葱", "番茄", "芝士"],
			icon: "cheeseburger.png",
		},

		chips: {
			index: 79,
			name: "chips",
			singular: "薯条",
			plural: "薯条",
			plant_cost: 400,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 20,
			multiplier: 1,
			special: ["vegan"],
			season: [],
			ingredients: ["potato", "vegetable_oil", "salt"], ingredients_cn: ["土豆", "植物油", "盐"],
			icon: "chips.png",
		},

		cheese_topped_trout: {
			index: 80,
			name: "cheese_topped_trout",
			singular: "芝士鳟鱼",
			plural: "芝士鳟鱼",
			plant_cost: 1600,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 20,
			multiplier: 1,
			special: ["seafood"],
			season: [],
			ingredients: ["trout", "bread", "cheese", "vegetable_oil", "butter", "lemon"],ingredients_cn: ["鳟鱼", "面包", "芝士", "植物油", "黄油", "柠檬"],
			icon: "cheese_topped_trout.png",
		},

		salmon: {
			index: 81,
			name: "salmon",
			singular: "鲑鱼",
			plural: "鲑鱼",
			plant_cost: 600,
			difficulty: 2,
			bed: "river",
			type: "seafood", type_cn: "海鲜",
			days: 1,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn"],
			ingredients: [],
			icon: "salmon.png",
			shop: ["supermarket"],
		},

		trout: {
			index: 82,
			name: "trout",
			singular: "鳟鱼",
			plural: "鳟鱼",
			plant_cost: 800,
			difficulty: 1,
			bed: "river",
			type: "seafood", type_cn: "海鲜",
			days: 1,
			multiplier: 1,
			special: [],
			season: ["autumn", "winter"],
			ingredients: [],
			icon: "trout.png",
			shop: ["supermarket"],
		},

		spaghetti_bolognese: {
			index: 83,
			name: "spaghetti_bolognese",
			singular: "肉酱意大利面",
			plural: "肉酱意大利面",
			plant_cost: 1100,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 30,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: ["pasta", "beef", "vegetable_oil", "garlic_bulb", "tomato"],ingredients_cn: ["意大利面", "牛肉", "植物油", "大蒜", "番茄"],
			icon: "spaghetti_bolognese.png",
		},

		lasagne: {
			index: 84,
			name: "lasagne",
			singular: "千层面",
			plural: "千层面",
			plant_cost: 1400,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: ["pasta", "beef", "cheese", "flour", "garlic_bulb", "tomato"], ingredients_cn: ["意大利面", "牛肉", "芝士", "面粉", "大蒜", "番茄"],
			icon: "lasagne.png",
		},

		carbonara: {
			index: 85,
			name: "carbonara",
			singular: "奶油培根意大利面",
			plural: "奶油培根意大利面",
			plant_cost: 1000,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 30,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: ["pasta", "cheese", "flour", "bottle_of_milk", "pork"],ingredients_cn: ["意大利面", "芝士", "面粉", "牛奶", "猪肉"],
			icon: "carbonara.png",
		},

		chicken_tikka_masala: {
			index: 86,
			name: "chicken_tikka_masala",
			singular: "鸡肉提卡",
			plural: "鸡肉提卡",
			plant_cost: 1700,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 45,
			multiplier: 1,
			special: ["spicy"],
			season: [],
			ingredients: ["chicken", "vegetable_oil", "onion", "garlic_bulb", "tomato", "butter", "lemon", "naan_bread", "rice"], ingredients_cn: ["鸡肉", "植物油", "洋葱", "大蒜", "番茄", "黄油", "柠檬", "馕饼", "米"],
			icon: "chicken_tikka_masala.png",
		},

		chilli_con_carne: {
			index: 87,
			name: "chilli_con_carne",
			singular: "墨西哥辣肉酱",
			plural: "墨西哥辣肉酱",
			plant_cost: 1300,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 45,
			multiplier: 1,
			special: ["spicy"],
			season: [],
			ingredients: ["beef", "vegetable_oil", "onion", "garlic_bulb", "tomato", "chilli_pepper"], ingredients_cn: ["牛肉", "植物油", "洋葱", "大蒜", "番茄", "辣椒"],
			icon: "chilli_con_carne.png",
		},

		rich_biscuit: {
			index: 88,
			name: "rich_biscuit",
			recipe_name: "rich biscuits",
			singular: "富贵饼干",
			plural: "富贵饼干",
			plant_cost: 50,
			difficulty: 1,
			handheld_gift: true,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 20,
			multiplier: 10,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["chicken_egg", "flour", "sugar", "lemon"], ingredients_cn: ["鸡蛋", "面粉", "糖", "柠檬"],
			icon: "rich_biscuit.png",
		},

		shortbread: {
			index: 89,
			name: "shortbread",
			singular: "黄油酥饼",
			plural: "黄油酥饼",
			plant_cost: 150,
			difficulty: 2,
			handheld_gift: true,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 35,
			multiplier: 5,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["butter", "flour", "sugar"], ingredients_cn: ["黄油", "面粉", "糖"],
			icon: "shortbread.png",
		},

		melting_moment: {
			index: 90,
			name: "melting_moment",
			recipe_name: "melting moments",
			singular: "入口即化饼干",
			plural: "入口即化饼干",
			plant_cost: 80,
			difficulty: 1,
			handheld_gift: true,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 20,
			multiplier: 5,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["butter", "flour", "sugar", "jam"], ingredients_cn: ["黄油", "面粉", "糖", "果酱"],
			icon: "melting_moment.png",
		},

		choc_chip_cookie: {
			index: 91,
			name: "choc_chip_cookie",
			recipe_name: "chocolate chip cookies",
			singular: "巧克力曲奇",
			plural: "巧克力曲奇",
			plant_cost: 100,
			difficulty: 1,
			handheld_gift: true,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 15,
			multiplier: 10,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["butter", "flour", "sugar", "chicken_egg", "chocolate"], ingredients_cn: ["黄油", "面粉", "糖", "鸡蛋", "巧克力"],
			icon: "choc_chip_cookie.png",
		},

		cocoa_powder: {
			index: 92,
			name: "cocoa_powder",
			singular: "杯装可可粉",
			plural: "杯装可可粉",
			plant_cost: 200,
			difficulty: 1,
			bed: "kitchen",
			type: "ingredient", type_cn: "食材",
			days: 1,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: [],
			icon: "cocoa_powder.png",
			shop: ["supermarket"],
			boughtInBulk: 5,
		},

		chocolate: {
			index: 93,
			name: "chocolate",
			singular: "巧克力",
			plural: "巧克力",
			plant_cost: 700,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 15,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["butter", "bottle_of_milk", "cocoa_powder"], ingredients_cn: ["黄油", "牛奶", "可可粉"],
			icon: "chocolate.png",
		},

		jammie_dodger: {
			index: 94,
			name: "jammie_dodger",
			recipe_name: "jammie dodgers",
			singular: "果酱夹心饼干",
			plural: "果酱夹心饼干",
			plant_cost: 80,
			difficulty: 1,
			handheld_gift: true,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 10,
			multiplier: 5,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["flour", "sugar", "butter", "chicken_egg", "jam"],ingredients_cn: ["面粉", "糖", "黄油", "鸡蛋", "果酱"],
			icon: "jammie_dodger.png",
		},

		jam: {
			index: 95,
			name: "jam",
			singular: "杯装果酱",
			plural: "杯装果酱",
			plant_cost: 200,
			difficulty: 1,
			bed: "kitchen",
			type: "ingredient", type_cn: "食材",
			days: 5,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: ["strawberry", "sugar"],ingredients_cn: ["草莓", "糖"],
			icon: "jam.png",
		},

		apple_strudel: {
			index: 94,
			name: "apple_strudel",
			recipe_name: "apple strudels",
			singular: "苹果卷",
			plural: "苹果卷",
			plant_cost: 1200,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 15,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["pastry", "apple", "sugar", "honey", "butter"],ingredients_cn: ["酥皮", "苹果", "糖", "蜂蜜", "黄油"],
			icon: "apple_strudel.png",
		},

		soufflé: {
			index: 95,
			name: "soufflé",
			recipe_name: "soufflés",
			singular: "舒芙蕾",
			plural: "舒芙蕾",
			plant_cost: 3000,
			difficulty: 4,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["chicken_egg", "cream", "sugar", "butter", "flour", "lemon"],ingredients_cn: ["鸡蛋", "奶油", "糖", "黄油", "面粉", "柠檬"],
			icon: "souffle.png",
		},

		tart: {
			index: 96,
			name: "tart",
			recipe_name: "tarts",
			singular: "水果挞",
			plural: "水果挞",
			plant_cost: 1000,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 30,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["pastry", "chocolate"],ingredients_cn: ["酥皮", "巧克力"],
			icon: "tart.png",
		},

		lemon_meringue_pie: {
			index: 97,
			name: "lemon_meringue_pie",
			singular: "柠檬酥皮派",
			plural: "柠檬酥皮派",
			plant_cost: 1600,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["pastry", "lemon", "sugar", "butter", "chicken_egg"],ingredients_cn: ["酥皮", "柠檬", "糖", "黄油", "鸡蛋"],
			icon: "lemon_meringue_pie.png",
		},

		sponge_cake: {
			index: 98,
			name: "sponge_cake",
			singular: "海绵蛋糕",
			plural: "海绵蛋糕",
			plant_cost: 1000,
			difficulty: 2,
			handheld_gift: true,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 25,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["flour", "butter", "sugar", "cream", "chicken_egg", "jam"],ingredients_cn: ["面粉", "黄油", "糖", "奶油", "鸡蛋", "果酱"],
			icon: "sponge_cake.png",
		},

		swiss_roll: {
			index: 99,
			name: "swiss_roll",
			recipe_name: "Swiss rolls",
			singular: "瑞士卷",
			plural: "瑞士卷",
			plant_cost: 1500,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 30,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["flour", "butter", "cream", "chicken_egg", "jam", "orange", "sugar"],ingredients_cn: ["面粉", "黄油", "奶油", "鸡蛋", "果酱", "橘子", "糖"],
			icon: "swiss_roll.png",
		},

		scone: {
			index: 100,
			name: "scone",
			recipe_name: "scones",
			singular: "司康饼",
			plural: "司康饼",
			plant_cost: 150,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 20,
			multiplier: 4,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["flour", "butter", "sugar", "salt", "bottle_of_milk"],ingredients_cn: ["面粉", "黄油", "糖", "盐", "牛奶"],
			icon: "scone.png",
		},

		brownie: {
			index: 101,
			name: "brownie",
			recipe_name: "brownies",
			singular: "布朗尼",
			plural: "布朗尼",
			plant_cost: 300,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 50,
			multiplier: 4,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["butter", "flour", "chocolate", "chicken_egg", "salt"],ingredients_cn: ["黄油", "面粉", "巧克力", "鸡蛋", "盐"],
			icon: "brownie.png",
		},

		carrot_cake: {
			index: 102,
			name: "carrot_cake",
			singular: "胡萝卜蛋糕",
			plural: "胡萝卜蛋糕",
			plant_cost: 1400,
			difficulty: 2,
			handheld_gift: true,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 50,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["wild_carrot", "sugar", "chicken_egg", "vegetable_oil", "flour", "lemon", "cream", "butter"],ingredients_cn: ["野生胡萝卜", "糖", "鸡蛋", "植物油", "面粉", "柠檬", "奶油", "黄油"],
			icon: "carrot_cake.png",
		},

		crème_brulee: {
			index: 103,
			name: "crème_brulee",
			singular: "烤布蕾",
			plural: "烤布蕾",
			plant_cost: 600,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 50,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["bottle_of_milk", "cream", "sugar", "chicken_egg"],ingredients_cn: ["牛奶", "奶油", "糖", "鸡蛋"],
			icon: "creme_brulee.png",
		},

		date: {
			index: 104,
			name: "date",
			singular: "椰枣",
			plural: "椰枣",
			plant_cost: 50,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 10,
			multiplier: 6,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "date.png",
			shop: ["supermarket"],
		},

		sticky_toffee_pudding: {
			index: 105,
			name: "sticky_toffee_pudding",
			singular: "太妃布丁",
			plural: "太妃布丁",
			plant_cost: 1200,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 25,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["date", "flour", "chicken_egg", "butter", "sugar", "bottle_of_milk", "cream"],ingredients_cn: ["椰枣", "面粉", "鸡蛋", "黄油", "糖", "牛奶", "奶油"],
			icon: "sticky_toffee_pudding.png",
		},

		chicken_vindaloo: {
			index: 106,
			name: "chicken_vindaloo",
			singular: "温达卢辣鸡肉咖喱",
			plural: "温达卢辣鸡肉咖喱",
			plant_cost: 1800,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 30,
			multiplier: 1,
			special: ["spicy"],
			season: [],
			ingredients: ["chicken", "vegetable_oil", "chilli_pepper", "onion", "tomato", "lemon", "garlic_bulb", "naan_bread", "rice"],ingredients_cn: ["鸡肉", "植物油", "辣椒", "洋葱", "番茄", "柠檬", "大蒜", "馕饼", "米"],
			icon: "chicken_vindaloo.png",
		},

		flapjack: {
			index: 107,
			name: "flapjack",
			recipe_name: "flapjack squares",
			singular: "燕麦小方",
			plural: "燕麦小方",
			plant_cost: 100,
			difficulty: 2,
			handheld_gift: true,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 25,
			multiplier: 6,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["butter", "sugar", "oats", "lemon"],ingredients_cn: ["黄油", "糖", "燕麦", "柠檬"],
			icon: "flapjack.png",
		},

		cherry: {
			index: 108,
			name: "cherry",
			singular: "樱桃",
			plural: "樱桃",
			plant_cost: 20,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 30,
			multiplier: 10,
			special: [],
			season: ["spring", "autumn", "winter"],
			ingredients: [],
			icon: "cherry.png",
			shop: ["supermarket"],
		},

		belgian_bun: {
			index: 109,
			name: "belgian_bun",
			recipe_name: "Belgian buns",
			singular: "比利时小圆面包",
			plural: "比利时小圆面包",
			plant_cost: 1000,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 10,
			special: ["sweet"],
			season: [],
			ingredients: ["flour", "sugar", "bottle_of_milk", "chicken_egg", "lemon", "cherry"],ingredients_cn: ["面粉", "糖", "牛奶", "鸡蛋", "柠檬", "樱桃"],
			icon: "belgian_bun.png",
		},

		lime: {
			index: 110,
			name: "lime",
			singular: "酸橙",
			plural: "酸橙",
			plant_cost: 250,
			difficulty: 1,
			bed: "earth",
			type: "fruit", type_cn: "水果",
			days: 12,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "lime.png",
			shop: ["supermarket"],
		},

		linguine: {
			index: 111,
			name: "linguine",
			singular: "扁意面",
			plural: "扁意面",
			plant_cost: 700,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 15,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["vegetable_oil", "lemon", "pasta", "cream"],ingredients_cn: ["植物油", "柠檬", "意大利面", "奶油"],
			icon: "linguine.png",
		},

		steak: {
			index: 112,
			name: "steak",
			singular: "牛排",
			plural: "牛排",
			plant_cost: 1000,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 25,
			multiplier: 1,
			special: ["carnivore"],
			season: [],
			ingredients: ["vegetable_oil", "beef"],ingredients_cn: ["植物油", "牛肉"],
			icon: "steak.png",
		},

		full_english_breakfast: {
			index: 113,
			name: "full_english_breakfast",
			recipe_name: "Full English breakfast",
			singular: "英式早餐",
			plural: "英式早餐",
			plant_cost: 900,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 25,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: ["vegetable_oil", "bacon", "sausage", "mushroom", "tomato", "chicken_egg"],ingredients_cn: ["植物油", "培根", "香肠", "蘑菇", "番茄", "鸡蛋"],
			icon: "full_english_breakfast.png",
		},

		apple_crumble: {
			index: 114,
			name: "apple_crumble",
			singular: "苹果酥",
			plural: "苹果酥",
			plant_cost: 700,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 35,
			multiplier: 1,
			special: ["sweet"],
			season: [],
			ingredients: ["apple", "sugar", "flour", "butter", "oats", "cream"],ingredients_cn: ["苹果", "糖", "面粉", "黄油", "燕麦", "奶油"],
			icon: "apple_crumble.png",
		},

		bakewell_tart: {
			index: 115,
			name: "bakewell_tart",
			recipe_name: "bakewell tarts",
			singular: "杏仁果酱挞",
			plural: "杏仁果酱挞",
			plant_cost: 1200,
			difficulty: 3,
			handheld_gift: true,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 35,
			multiplier: 1,
			special: ["sweet"],
			season: [],
			ingredients: ["shortbread", "cream", "cherry"],ingredients_cn: ["黄油酥饼", "奶油", "樱桃"],
			icon: "bakewell_tart.png",
		},

		cod: {
			index: 116,
			name: "cod",
			singular: "鳕鱼",
			plural: "鳕鱼",
			plant_cost: 600,
			difficulty: 1,
			bed: "sea",
			type: "seafood", type_cn: "海鲜",
			days: 1,
			multiplier: 1,
			special: [],
			season: ["winter"],
			ingredients: [],
			icon: "cod.png",
			shop: ["supermarket"],
		},

		fish_and_chips: {
			index: 117,
			name: "fish_and_chips",
			singular: "炸鱼薯条",
			plural: "炸鱼薯条",
			plant_cost: 1400,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 30,
			multiplier: 1,
			special: ["seafood"],
			season: [],
			ingredients: ["cod", "chips", "vegetable_oil", "flour"],ingredients_cn: ["鳕鱼", "薯条", "植物油", "面粉"],
			icon: "fish_and_chips.png",
		},

		clam: {
			index: 118,
			name: "clam",
			singular: "蛤蜊",
			plural: "蛤蜊",
			plant_cost: 400,
			difficulty: 1,
			bed: "sea",
			type: "seafood", type_cn: "海鲜",
			days: 1,
			multiplier: 1,
			special: [],
			season: ["spring", "autumn", "winter"],
			ingredients: [],
			icon: "clam.png",
			shop: ["supermarket"],
		},

		clam_chowder: {
			index: 119,
			name: "clam_chowder",
			singular: "蛤蜊浓汤",
			plural: "蛤蜊浓汤",
			plant_cost: 1300,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 30,
			multiplier: 1,
			special: ["seafood"],
			season: [],
			ingredients: ["clam", "butter", "bacon", "onion", "flour", "bottle_of_milk", "cream", "potato"],ingredients_cn: ["蛤蜊", "黄油", "培根", "洋葱", "面粉", "牛奶", "奶油", "土豆"],
			icon: "clam_chowder.png",
		},

		cheese_and_crackers: {
			index: 120,
			name: "cheese_and_crackers",
			singular: "芝士与饼干",
			plural: "芝士与饼干",
			plant_cost: 800,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 25,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["flour", "salt", "sugar", "vegetable_oil", "cheese"],ingredients_cn: ["面粉", "盐", "糖", "植物油", "芝士"],
			icon: "cheese_and_crackers.png",
		},

		bangers_and_mash: {
			index: 121,
			name: "bangers_and_mash",
			singular: "土豆泥和香肠",
			plural: "土豆泥和香肠",
			plant_cost: 1200,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: ["vegetable_oil", "sausage", "butter", "bottle_of_milk", "potato"],ingredients_cn: ["植物油", "香肠", "黄油", "牛奶", "土豆"],
			icon: "bangers_and_mash.png",
		},

		yorkshire_pudding: {
			index: 122,
			name: "yorkshire_pudding",
			singular: "约克郡布丁",
			plural: "约克郡布丁",
			plant_cost: 1200,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["flour", "chicken_egg", "bottle_of_milk", "vegetable_oil"],ingredients_cn: ["面粉", "鸡蛋", "牛奶", "植物油"],
			icon: "yorkshire_pudding.png",
		},

		stuffing: {
			index: 123,
			name: "stuffing",
			cn_name_cap: "馅料",singular: "馅料丸子",
			plural: "馅料丸子",
			plant_cost: 100,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 6,
			special: ["vegetarian"],
			season: [],
			ingredients: ["butter", "vegetable_oil", "onion", "garlic_bulb", "bread", "chicken_egg"], ingredients_cn: ["黄油", "植物油", "洋葱", "大蒜", "面包", "鸡蛋"],
			icon: "stuffing.png",
		},

		roast_dinner: {
			index: 124,
			name: "roast_dinner",
			recipe_name: "roast dinner",
			singular: "晚餐烤肉",
			plural: "晚餐烤肉",
			plant_cost: 2400,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 60,
			multiplier: 1,
			special: [],
			season: [],
			ingredients_cn: ["约克郡布丁","馅料","鸡肉","牛排","猪肉","土豆","野生胡萝卜","卷心菜","洋葱","大头菜","植物油","盐"], ingredients: [
				"yorkshire_pudding",
				"stuffing",
				"chicken",
				"beef",
				"pork",
				"potato",
				"wild_carrot",
				"cabbage",
				"onion",
				"turnip",
				"vegetable_oil",
				"salt",
			],
			icon: "roast_dinner.png",
		},

		crumpet: {
			index: 125,
			name: "crumpet",
			recipe_name: "crumpets",
			singular: "松脆饼",
			plural: "松脆饼",
			plant_cost: 100,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 20,
			multiplier: 5,
			special: ["vegetarian"],
			season: [],
			ingredients: ["flour", "butter", "salt", "sugar"],ingredients_cn: ["面粉", "黄油", "盐", "糖"],
			icon: "crumpet.png",
		},

		orange_juice: {
			index: 126,
			name: "orange_juice",
			singular: "杯装橙汁",
			plural: "杯装橙汁",
			plant_cost: 55,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 5,
			multiplier: 2,
			special: ["vegan", "drink"],
			season: [],
			ingredients: ["orange", "sugar"],ingredients_cn: ["橘子", "糖"],
			icon: "orange_juice.png",
		},

		lemonade: {
			index: 127,
			name: "lemonade",
			singular: "杯装柠檬水",
			plural: "杯装柠檬水",
			plant_cost: 100,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 5,
			multiplier: 2,
			special: ["vegan", "drink"],
			season: [],
			ingredients: ["lemon", "sugar"],ingredients_cn: ["柠檬", "糖"],
			icon: "lemonade.png",
		},

		banana_bread: {
			index: 128,
			name: "banana_bread",
			singular: "香蕉面包",
			plural: "香蕉面包",
			plant_cost: 500,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 25,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["butter", "sugar", "chicken_egg", "flour", "banana"],ingredients_cn: ["黄油", "糖", "鸡蛋", "面粉", "香蕉"],
			icon: "banana_bread.png",
		},

		red_wine: {
			index: 129,
			name: "red_wine",
			singular: "红酒",
			plural: "红酒",
			plant_cost: 600,
			difficulty: 1,
			bed: "kitchen",
			type: "ingredient", type_cn: "食材",
			days: 21,
			multiplier: 1,
			special: ["vegetarian", "drink", "alcohol"],
			season: [],
			ingredients: [],
			icon: "red_wine.png",
			shop: ["supermarket"],
		},

		white_wine: {
			index: 130,
			name: "white_wine",
			singular: "白葡萄酒",
			plural: "白葡萄酒",
			plant_cost: 600,
			difficulty: 1,
			bed: "kitchen",
			type: "ingredient", type_cn: "食材",
			days: 21,
			multiplier: 1,
			special: ["vegetarian", "drink", "alcohol"],
			season: [],
			ingredients: [],
			icon: "white_wine.png",
			shop: ["supermarket"],
		},

		poached_pear: {
			index: 131,
			name: "poached_pear",
			recipe_name: "poached pears",
			singular: "蜜梨",
			plural: "蜜梨",
			plant_cost: 1000,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 21,
			multiplier: 1,
			special: ["vegan", "alcohol", "sweet"],
			season: [],
			ingredients: ["pear", "sugar", "red_wine"],ingredients_cn: ["梨子", "糖", "红葡萄酒"],
			icon: "poached_pear.png",
		},

		peach_panzanella: {
			index: 132,
			name: "peach_panzanella",
			singular: "意式蜜桃沙拉",
			plural: "意式蜜桃沙拉",
			plant_cost: 600,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 30,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["peach", "bread", "cheese", "vegetable_oil", "lemon"],ingredients_cn: ["桃子", "面包", "芝士", "植物油", "柠檬"],
			icon: "peach_panzanella.png",
		},

		plum_pudding: {
			index: 133,
			name: "plum_pudding",
			singular: "李子布丁",
			plural: "李子布丁",
			plant_cost: 1400,
			difficulty: 3,
			handheld_gift: true,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 25,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["plum", "flour", "bread", "sugar", "orange", "lemon", "cherry", "wild_carrot"],ingredients_cn: ["李子", "面粉", "面包", "糖", "橘子", "柠檬", "樱桃", "野生胡萝卜"],
			icon: "plum_pudding.png",
		},

		spinach: {
			index: 134,
			name: "spinach",
			seed_name: "菠菜",
			singular: "菠菜叶",
			plural: "菠菜叶",
			plant_cost: 10,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 10,
			multiplier: 10,
			special: [],
			season: ["spring", "autumn"],
			ingredients: [],
			icon: "spinach.png",
		},

		salad: {
			index: 135,
			name: "salad",
			singular: "沙拉",
			plural: "沙拉",
			plant_cost: 1100,
			difficulty: 2,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 10,
			multiplier: 1,
			special: ["vegan"],
			season: [],
			ingredients: ["spinach", "tomato", "onion", "garlic_bulb", "chilli_pepper", "pepper", "lime"],ingredients_cn: ["菠菜", "番茄", "洋葱", "大蒜", "辣椒", "灯笼椒", "酸橙"],
			icon: "salad.png",
		},

		arancini: {
			index: 136,
			name: "arancini",
			singular: "意式炸饭球",
			plural: "意式炸饭球",
			plant_cost: 700,
			difficulty: 3,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 40,
			multiplier: 4,
			special: ["vegetarian"],
			season: [],
			ingredients: ["vegetable_oil", "butter", "onion", "rice", "garlic_bulb", "white_wine", "cheese", "lemon", "flour", "chicken_egg", "truffle"],ingredients_cn: ["植物油", "黄油", "洋葱", "米", "大蒜", "白葡萄酒", "芝士", "柠檬", "面粉", "鸡蛋", "松露"],
			icon: "arancini.png",
		},

		wolfbrew: {
			index: 137,
			name: "wolfbrew",
			singular: "狼菇酒",
			plural: "狼菇酒",
			plant_cost: 3000,
			difficulty: 5,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 60,
			multiplier: 1,
			special: ["vegetarian", "drink", "alcohol", "tainted"],
			season: [],
			ingredients: ["wolfshroom", "red_wine", "strange_flower"],ingredients_cn: ["狼菇", "红葡萄酒", "诡异的花"],
			icon: "wolfbrew.png",
		},

		ghostbrew: {
			index: 138,
			name: "ghostbrew",
			singular: "幽灵菇酒",
			plural: "幽灵菇酒",
			plant_cost: 3000,
			difficulty: 5,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 60,
			multiplier: 1,
			special: ["vegetarian", "drink", "alcohol", "tainted"],
			season: [],
			ingredients: ["ghostshroom", "white_wine", "strange_flower"],ingredients_cn: ["幽灵菇", "白葡萄酒", "诡异的"],
			icon: "ghostbrew.png",
		},

		beef: {
			index: 139,
			name: "beef",
			singular: "牛肉",
			plural: "牛肉",
			plant_cost: 1000,
			difficulty: 1,
			bed: "kitchen",
			type: "meat", type_cn: "肉类",
			days: 10,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: [],
			icon: "beef.png",
			shop: ["supermarket"],
		},

		pork: {
			index: 140,
			name: "pork",
			singular: "猪肉",
			plural: "猪肉",
			plant_cost: 700,
			difficulty: 1,
			bed: "kitchen",
			type: "meat", type_cn: "肉类",
			days: 10,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: [],
			icon: "pork.png",
			shop: ["supermarket"],
		},

		cauliflower: {
			index: 141,
			name: "cauliflower",
			singular: "花椰菜",
			plural: "花椰菜",
			plant_cost: 480,
			difficulty: 1,
			bed: "earth",
			type: "vegetable", type_cn: "蔬菜",
			days: 30,
			multiplier: 1,
			special: [],
			season: ["spring", "summer", "autumn", "winter"],
			ingredients: [],
			icon: "cauliflower.png",
		},

		oats: {
			index: 142,
			name: "oats",
			singular: "杯装燕麦",
			plural: "杯装燕麦",
			plant_cost: 100,
			difficulty: 1,
			bed: "kitchen",
			type: "ingredient", type_cn: "食材",
			days: 1,
			multiplier: 1,
			special: [],
			season: [],
			ingredients: [],
			icon: "oats.png",
			shop: ["supermarket"],
			boughtInBulk: 5,
		},

		prawn: {
			index: 143,
			name: "prawn",
			singular: "大虾",
			plural: "大虾",
			plant_cost: 300,
			difficulty: 1,
			bed: "sea",
			type: "seafood", type_cn: "海鲜",
			days: 1,
			multiplier: 1,
			special: [],
			season: ["summer", "autumn", "winter"],
			ingredients: [],
			icon: "prawn.png",
			shop: ["supermarket"],
		},

		omelette: {
			index: 144,
			name: "omelette",
			recipe_name: "omelettes",
			singular: "煎蛋卷",
			plural: "煎蛋卷",
			plant_cost: 300,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 5,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["chicken_egg", "vegetable_oil", "butter"],ingredients_cn: ["鸡蛋", "植物油", "黄油"],
			icon: "omelette.png",
		},

		porridge: {
			index: 145,
			name: "porridge",
			singular: "麦片粥",
			plural: "麦片粥",
			plant_cost: 250,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 5,
			multiplier: 1,
			special: ["vegetarian"],
			season: [],
			ingredients: ["oats", "bottle_of_milk"],ingredients_cn: ["燕麦", "牛奶"],
			icon: "porridge.png",
		},

		turnip_soup: {
			index: 146,
			name: "turnip_soup",
			singular: "萝卜浓汤",
			plural: "萝卜浓汤",
			plant_cost: 250,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 15,
			multiplier: 1,
			special: ["vegan"],
			season: [],
			ingredients: ["turnip", "potato", "onion", "vegetable_oil", "salt"],ingredients_cn: ["萝卜", "土豆", "洋葱", "植物油", "盐"],
			icon: "turnip_soup.png",
		},

		pink_rose: {
			index: 147,
			name: "pink_rose",
			plural: "粉玫瑰",
			plant_cost: 1200,
			difficulty: 3,
			bed: "earth",
			type: "flower", type_cn: "花朵",
			days: 14,
			multiplier: 1,
			special: [],
			season: ["spring", "autumn"],
			ingredients: [],
			icon: "pink_rose.png",
		},

		valentines_chocolate: {
			index: 148,
			name: "valentines_chocolate",
			singular: "情人节巧克力",
			plural: "情人节巧克力",
			plant_cost: 900,
			difficulty: 1,
			bed: "kitchen",
			type: "food", type_cn: "食物",
			days: 15,
			multiplier: 1,
			special: ["vegetarian", "sweet"],
			season: [],
			ingredients: ["butter", "bottle_of_milk", "cocoa_powder", "pear"], ingredients_cn: ["黄油", "牛奶", "可可粉", "梨"],
			icon: "valentines_chocolate.png",
		},
	};

	/*
		Sorts all plants alphabetically after their initialisation into _plants.
		This is so Object.values/keys will read them based on their alphabetical key order.
		Yet allows extras to be added easily based on .index being available and ordered above.
	*/
	const sorted = Object.keys(plants).sort();
	setup.SG_OldPlants = {};
	sorted.forEach(s => {
		setup.SG_OldPlants[s] = plants[s];
	});
	
}

initSGOldPlants();











